### ISSUE TITLE
[Bug]: Fantia downloads failed

### ISSUE THREAD

**Issue by zxgbs** [KJHJason/Cultured-Downloader#28]
### Which program are you seeing this problem on?

Cultured Downloader (exe)

### Program Version

4.2.1

### Steps to reproduce the bug

1. choose    1. Download Fantia Posts
2. choose   1. Download images from Fantia post(s)
3. Enter URL(s) (X to cancel): https://fantia.jp/posts/1704263
4. 
Do you wish to download from these URLs? (Y/n): y
Download images? (Y/n/x to cancel): y
Download thumbnail? (Y/n/x to cancel): y
Download attachments? (Y/n/x to cancel): y

### Expected behaviour

the post should have been downloaded

### Relevant log output (If any)

the log says:
Failed to get the details of 'https://fantia.jp/posts/1704263' after 4 requests.

**Comment by KJHJason** [comment]
I was able to locate the issue, turns out Fantia's API now requires a `x-csrf-token` in the request header. Otherwise, a 403 Forbidden response will be returned.

This `x-csrf-token` value can be retrieved from the HTML's meta tag while logged in,
`<meta name="csrf-token" content="...">`

I am currently fixing this issue in the CLI version before integrating this Python program with the golang CLI program.

**Comment by KJHJason** [comment]
I have fixed the issue and released a new version, [v4.2.2](https://github.com/KJHJason/Cultured-Downloader/releases/tag/4.2.2).

Please re-open this issue if the issue still persists on your end.
