### ISSUE TITLE
[Bug]: Can't log in due to chrome not recognizing the browser the script prompted

### ISSUE THREAD

**Issue by KiKaloko** [KJHJason/Cultured-Downloader#56]
### Which program are you seeing this problem on?

Cultured Downloader (exe)

### Program Version

latest

### Steps to reproduce the bug

there are none, I just did what was told and I can't log in to neither fantia or fanbox

### Expected behaviour

I expected for things to go down smoothly but I guess that's was too much to hope for.

**Comment by KJHJason** [comment]
Login on my end still works. Hence, I am unable to replicate and pinpoint the issue faced on your end without more details.

Did a browser popup as the program prompts you to login?
If there wasn't any new window of a browser, it could be due to your antivirus flagging chromedriver.exe as a malware.
